### ISSUE TITLE
PwnBack Is the same project/forked version  as Wayback Machine

### ISSUE THREAD

**Issue by Green-Wolf** [snoopysecurity/awesome-burp-extensions#1]
Hey, what a fantastic list you've put togeather. I was just going through updating my extensions and i noticed that two of the projects listed seem to be the same. 

PwnBack - Burp Extender plugin that generates a sitemap of a website using Wayback Machine.
Wayback Machine - Generate a sitemap using Wayback Machine..

https://github.com/P3GLEG/PwnBack
https://portswigger.net/bappstore/5c7c516c690345c19fbf55b2b2ebeb76
https://github.com/PortSwigger/wayback-machine/network

**Comment by Green-Wolf** [comment]
Burplay - Burplay is a Burp Extension allowing for replaying any number of requests using same modifications definition. Its main purpose is to aid in searching for Privilege Escalation issues.
Multi Session Replay - This extension allows replay of requests in multiple sessions.

These two are also the same, just Portswigger renaming Burplay to Multi Session Replay when they put it in the app store.

**Comment by snoopysecurity** [comment]
Hi, good spot! i have removed the duplicates and mentioned both names as part of one extension description as a reference
